# Generated by Django 5.0.3 on 2024-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Car_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField()),
                ('submodel', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('MIN_SUM_INSURED', models.IntegerField()),
                ('MAX_SUM_INSURED', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
                ('campaign', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_insured', models.CharField(max_length=25)),
                ('premium', models.IntegerField()),
                ('campaign', models.IntegerField()),
                ('age', models.CharField(max_length=5)),
                ('deduct', models.CharField(max_length=100)),
                ('garage', models.CharField(max_length=10)),
            ],
        ),
    ]
