# Generated by Django 5.0.3 on 2024-03-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.car')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.premium')),
            ],
        ),
    ]
