# Generated by Django 5.0.3 on 2024-03-29 14:02

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0002_premium_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Owned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.IntegerField()),
                ('province', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='premium',
            name='cars',
            field=models.ManyToManyField(related_name='premium', through='ipc.Premium_Car', to='ipc.car'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('tel', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('car_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.car_owned')),
            ],
        ),
    ]
