# Generated by Django 5.0.3 on 2024-03-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_car_owned_province_remove_premium_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.campaign'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.campaign'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='max_age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='max_sum_insured',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='min_age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='min_sum_insured',
            field=models.IntegerField(null=True),
        ),
    ]
