# Generated by Django 5.0.3 on 2024-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0004_alter_coverage_campaign_alter_premium_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='min_year',
            field=models.IntegerField(null=True),
        ),
    ]
